// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfMcpev4TWt3yst8pNID9Qicu6vX8Q9E',
    appId: '1:116446779617:web:900c877e31be663e3cffa0',
    messagingSenderId: '116446779617',
    projectId: 'qu2s-e9232',
    authDomain: 'qu2s-e9232.firebaseapp.com',
    storageBucket: 'qu2s-e9232.appspot.com',
    measurementId: 'G-SG49QLLBF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4pTIW_5TFnZq5h8ViZra-SUHzAQEpsY',
    appId: '1:116446779617:android:e3a311c0658bc77b3cffa0',
    messagingSenderId: '116446779617',
    projectId: 'qu2s-e9232',
    storageBucket: 'qu2s-e9232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhXnREcVTPAoiuqE82dp_n-h_jAOYdbA',
    appId: '1:116446779617:ios:bb3e44433dfc8afc3cffa0',
    messagingSenderId: '116446779617',
    projectId: 'qu2s-e9232',
    storageBucket: 'qu2s-e9232.appspot.com',
    iosClientId: '116446779617-l36u9lel1rgr7110abds01gq95sp0slj.apps.googleusercontent.com',
    iosBundleId: 'com.example.qu2s',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyhXnREcVTPAoiuqE82dp_n-h_jAOYdbA',
    appId: '1:116446779617:ios:bb3e44433dfc8afc3cffa0',
    messagingSenderId: '116446779617',
    projectId: 'qu2s-e9232',
    storageBucket: 'qu2s-e9232.appspot.com',
    iosClientId: '116446779617-l36u9lel1rgr7110abds01gq95sp0slj.apps.googleusercontent.com',
    iosBundleId: 'com.example.qu2s',
  );
}
